/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * Almacen API
 * OpenAPI spec version: 1.0.0
 */

export interface CambiarMiContrasena {
  /** @maxLength 50 */
  contrasena_actual: string;
  /** @maxLength 50 */
  contrasena_nueva: string;
  /** @maxLength 50 */
  repetir_contrasena_nueva: string;
}
