/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * Almacen API
 * OpenAPI spec version: 1.0.0
 */

export interface CategoriaProductoSchema {
  id?: number | null;
  fecha_creacion: string;
  fecha_actualizacion: string;
  /** @maxLength 100 */
  nombre: string;
}
