/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * Almacen API
 * OpenAPI spec version: 1.0.0
 */

export interface DashboardEstadisticas {
  fecha_hora_actual: string;
  usuario_autenticado_nombre: string;
  usuario_autenticado_sucursal: string;
  cantidad_proveedores: number;
  cantidad_productos: number;
  cantidad_pedidos_hechos_pendientes: number;
  cantidad_pedidos_hechos_completados: number;
  cantidad_pedidos_recibidos_pendientes: number;
  cantidad_pedidos_recibidos_completados: number;
}
