/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * Almacen API
 * OpenAPI spec version: 1.0.0
 */

export interface DetallePedidoSchema {
  id?: number | null;
  created_at: string;
  updated_at: string;
  pedido: number;
  producto: number;
  cantidad: number;
}
