/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * Almacen API
 * OpenAPI spec version: 1.0.0
 */

export interface Input {
  /** @minimum 1 */
  limit?: number;
  /** @minimum 0 */
  offset?: number;
}
