/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * Almacen API
 * OpenAPI spec version: 1.0.0
 */

export interface LoginRequest {
  /** @maxLength 50 */
  nombre: string;
  /** @maxLength 50 */
  contrasena: string;
}
