/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * Almacen API
 * OpenAPI spec version: 1.0.0
 */
import type { Proveedor } from './proveedor';

export interface PagedProveedor {
  items: Proveedor[];
  count: number;
}
