/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * Almacen API
 * OpenAPI spec version: 1.0.0
 */
import type { ProveedorSchema } from './proveedorSchema';

export interface PagedProveedorSchema {
  items: ProveedorSchema[];
  count: number;
}
