/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * Almacen API
 * OpenAPI spec version: 1.0.0
 */
import type { PedidoSchema } from './pedidoSchema';

export interface PagedPedidoSchema {
  items: PedidoSchema[];
  count: number;
}
