/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * Almacen API
 * OpenAPI spec version: 1.0.0
 */
import type { ProductoSucursalSchema } from './productoSucursalSchema';

export interface PagedProductoSucursalSchema {
  items: ProductoSucursalSchema[];
  count: number;
}
