/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * Almacen API
 * OpenAPI spec version: 1.0.0
 */
import type { UsuarioSchema } from './usuarioSchema';

export interface PagedUsuarioSchema {
  items: UsuarioSchema[];
  count: number;
}
