/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * Almacen API
 * OpenAPI spec version: 1.0.0
 */
import type { Pedido } from './pedido';

export interface PagedPedido {
  items: Pedido[];
  count: number;
}
