/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * Almacen API
 * OpenAPI spec version: 1.0.0
 */

export interface PedidoCopiaItem {
  proveedor_id: number;
  /** @maxLength 50 */
  proveedor_nombre: string;
  producto_id: number;
  /** @maxLength 50 */
  producto_nombre: string;
  cantidad: number;
  fecha_creacion: string;
}
