/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * Almacen API
 * OpenAPI spec version: 1.0.0
 */
import type { PedidoCreateEstado } from './pedidoCreateEstado';

export interface PedidoCreate {
  usuario_destino_id?: number | null;
  estado?: PedidoCreateEstado;
}
