/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * Almacen API
 * OpenAPI spec version: 1.0.0
 */

export interface PedidoSchema {
  id?: number | null;
  created_at: string;
  updated_at: string;
  sucursal_origen: number;
  sucursal_destino: number;
  /** @maxLength 20 */
  estado?: string;
  fecha_pedido: string;
}
