/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * Almacen API
 * OpenAPI spec version: 1.0.0
 */

export type PedidoCreateEstado = typeof PedidoCreateEstado[keyof typeof PedidoCreateEstado];


export const PedidoCreateEstado = {
  pendiente: 'pendiente',
  completado: 'completado',
} as const;
