/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * Almacen API
 * OpenAPI spec version: 1.0.0
 */

export interface Pedido {
  creado_por_nombre?: string | null;
  usuario_destino_nombre?: string | null;
  id?: number | null;
  fecha_creacion: string;
  fecha_actualizacion: string;
  creado_por: number;
  usuario_destino?: number | null;
  /** @maxLength 20 */
  estado?: string;
}
