/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * Almacen API
 * OpenAPI spec version: 1.0.0
 */

export type PedidoCambiarEstadoEstado = typeof PedidoCambiarEstadoEstado[keyof typeof PedidoCambiarEstadoEstado];


export const PedidoCambiarEstadoEstado = {
  pendiente: 'pendiente',
  completado: 'completado',
} as const;
