/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * Almacen API
 * OpenAPI spec version: 1.0.0
 */
import type { PedidoCopiaItem } from './pedidoCopiaItem';

export interface PedidoCopiaResumen {
  pedido_id: number;
  estado: string;
  creado_por_nombre?: string | null;
  usuario_destino_nombre?: string | null;
  proveedor_id?: number | null;
  proveedor_nombre?: string | null;
  fecha_creacion: string;
  fecha_actualizacion: string;
  cantidad_total_productos: number;
  productos: PedidoCopiaItem[];
}
