/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * Almacen API
 * OpenAPI spec version: 1.0.0
 */

export interface PedidoProveedorResumen {
  proveedor_id: number;
  proveedor_nombre: string;
  cantidad_productos_pedidos: number;
}
