/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * Almacen API
 * OpenAPI spec version: 1.0.0
 */

export interface PedidoDetalle {
  producto_nombre?: string | null;
  producto_imagen?: string | null;
  id?: number | null;
  fecha_creacion: string;
  fecha_actualizacion: string;
  pedido: number;
  producto: number;
  cantidad: number;
}
