/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * Almacen API
 * OpenAPI spec version: 1.0.0
 */

export interface PedidoCreateSchema {
  sucursal_origen_id: number;
  sucursal_destino_id: number;
  estado?: string;
}
