/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * Almacen API
 * OpenAPI spec version: 1.0.0
 */

export interface ProductoCreate {
  proveedor_id: number;
  /** @maxLength 50 */
  nombre: string;
  descripcion?: string | null;
  precio_compra?: number | string | null;
  precio_venta?: number | string | null;
  categoria_id?: number | null;
}
