/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * Almacen API
 * OpenAPI spec version: 1.0.0
 */

export interface ProductoSucursalSchema {
  id?: number | null;
  created_at: string;
  updated_at: string;
  producto: number;
  sucursal: number;
  cantidad?: number;
}
