/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * Almacen API
 * OpenAPI spec version: 1.0.0
 */

export interface ProductoUpdate {
  proveedor_id?: number | null;
  nombre?: string | null;
  descripcion?: string | null;
  precio_compra?: number | string | null;
  precio_venta?: number | string | null;
  categoria_id?: number | null;
}
