/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * Almacen API
 * OpenAPI spec version: 1.0.0
 */

export interface ProductoSchema {
  id?: number | null;
  created_at: string;
  updated_at: string;
  /** @maxLength 100 */
  nombre: string;
  imagen?: string | null;
  descripcion?: string | null;
  /** @pattern ^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$ */
  precio: string;
  proveedor: number;
  categoria?: string | null;
}
