/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * Almacen API
 * OpenAPI spec version: 1.0.0
 */

export interface ProductoDetail {
  proveedor_nombre?: string | null;
  categoria_nombre?: string | null;
  id?: number | null;
  fecha_creacion: string;
  fecha_actualizacion: string;
  proveedor: number;
  /** @maxLength 100 */
  nombre: string;
  imagen?: string | null;
  descripcion?: string | null;
  precio_compra?: string | null;
  precio_venta?: string | null;
  categoria?: number | null;
}
