/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * Almacen API
 * OpenAPI spec version: 1.0.0
 */

export interface ProductoUpdateSchema {
  nombre?: string | null;
  descripcion?: string | null;
  precio?: number | string | null;
  proveedor_id?: number | null;
  categoria?: string | null;
}
