/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * Almacen API
 * OpenAPI spec version: 1.0.0
 */

export interface ProductoCreateSchema {
  nombre: string;
  descripcion?: string | null;
  precio: number | string;
  proveedor_id: number;
  categoria?: string | null;
}
