/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * Almacen API
 * OpenAPI spec version: 1.0.0
 */

export interface ProductoSucursalCreateSchema {
  producto_id: number;
  sucursal_id: number;
  cantidad: number;
}
