/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * Almacen API
 * OpenAPI spec version: 1.0.0
 */

export interface ProveedorCreate {
  /** @maxLength 50 */
  nombre: string;
  telefono?: string | null;
  cuenta_bancaria?: string | null;
}
