/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * Almacen API
 * OpenAPI spec version: 1.0.0
 */

export interface SucursalSchema {
  id?: number | null;
  created_at: string;
  updated_at: string;
  /** @maxLength 100 */
  nombre: string;
  direccion?: string | null;
  /** @maxLength 20 */
  tipo: string;
}
