/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * Almacen API
 * OpenAPI spec version: 1.0.0
 */

export interface SucursalUsuarioCreateSchema {
  sucursal_id: number;
  usuario_id: number;
  rol?: string;
}
