/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * Almacen API
 * OpenAPI spec version: 1.0.0
 */

export interface SucursalCreateSchema {
  nombre: string;
  direccion?: string | null;
  tipo: string;
}
