/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * Almacen API
 * OpenAPI spec version: 1.0.0
 */

export interface SucursalUsuarioSchema {
  id?: number | null;
  created_at: string;
  updated_at: string;
  sucursal: number;
  usuario: number;
  /** @maxLength 20 */
  rol?: string;
}
