/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * Almacen API
 * OpenAPI spec version: 1.0.0
 */
import type { UsuarioCreateRol } from './usuarioCreateRol';

export interface UsuarioCreate {
  nombre: string;
  contrasena: string;
  nombre_sucursal: string;
  rol?: UsuarioCreateRol;
}
