/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * Almacen API
 * OpenAPI spec version: 1.0.0
 */

export interface Usuario {
  id?: number | null;
  fecha_creacion: string;
  fecha_actualizacion: string;
  /** @maxLength 50 */
  nombre: string;
  /** @maxLength 50 */
  nombre_sucursal: string;
  /** @maxLength 50 */
  rol?: string;
}
