/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * Almacen API
 * OpenAPI spec version: 1.0.0
 */

export type UsuarioCreateRol = typeof UsuarioCreateRol[keyof typeof UsuarioCreateRol];


export const UsuarioCreateRol = {
  admin_general: 'admin_general',
  admin_sucursal: 'admin_sucursal',
} as const;
