/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * Almacen API
 * OpenAPI spec version: 1.0.0
 */

export interface UsuarioSchema {
  id?: number | null;
  created_at: string;
  updated_at: string;
  /** @maxLength 50 */
  nombre_usuario: string;
  /** @maxLength 20 */
  rol?: string;
}
