/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * Almacen API
 * OpenAPI spec version: 1.0.0
 */

export interface UsuarioUpdate {
  nombre?: string | null;
  contrasena?: string | null;
  nombre_sucursal?: string | null;
  rol?: 'admin_general' | 'admin_sucursal' | null;
}
