/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * Almacen API
 * OpenAPI spec version: 1.0.0
 */
import type {
  DetallePedidoCreateSchema,
  DetallePedidoSchema,
  DetallePedidoUpdateSchema,
  LoginResponseSchema,
  LoginSchema,
  PagedDetallePedidoSchema,
  PagedPedidoSchema,
  PagedProductoSchema,
  PagedProductoSucursalSchema,
  PagedProveedorSchema,
  PagedProveedorUsuarioSchema,
  PagedSucursalSchema,
  PagedSucursalUsuarioSchema,
  PagedUsuarioSchema,
  PedidoApiListDetallesParams,
  PedidoApiListPedidosParams,
  PedidoCreateSchema,
  PedidoSchema,
  PedidoUpdateSchema,
  ProductoApiCreateProductoBody,
  ProductoApiListInventarioParams,
  ProductoApiListProductosParams,
  ProductoApiUpdateProductoBody,
  ProductoSchema,
  ProductoSucursalCreateSchema,
  ProductoSucursalSchema,
  ProductoSucursalUpdateSchema,
  ProveedorApiListProveedorUsuariosParams,
  ProveedorApiListProveedoresParams,
  ProveedorCreateSchema,
  ProveedorSchema,
  ProveedorUpdateSchema,
  ProveedorUsuarioCreateSchema,
  ProveedorUsuarioSchema,
  ProveedorUsuarioUpdateSchema,
  SucursalApiListSucursalUsuariosParams,
  SucursalApiListSucursalesParams,
  SucursalCreateSchema,
  SucursalSchema,
  SucursalUpdateSchema,
  SucursalUsuarioCreateSchema,
  SucursalUsuarioSchema,
  SucursalUsuarioUpdateSchema,
  UsuarioApiListUsuariosParams,
  UsuarioCreateSchema,
  UsuarioSchema,
  UsuarioUpdateSchema
} from './schemas';

/**
 * @summary Login Usuario
 */
export type usuarioApiLoginUsuarioResponse200 = {
  data: LoginResponseSchema
  status: 200
}

export type usuarioApiLoginUsuarioResponseSuccess = (usuarioApiLoginUsuarioResponse200) & {
  headers: Headers;
};
;

export type usuarioApiLoginUsuarioResponse = (usuarioApiLoginUsuarioResponseSuccess)

export const getUsuarioApiLoginUsuarioUrl = () => {


  

  return `/api/usuarios/login`
}

export const usuarioApiLoginUsuario = async (loginSchema: LoginSchema, options?: RequestInit): Promise<usuarioApiLoginUsuarioResponse> => {
  
  const res = await fetch(getUsuarioApiLoginUsuarioUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      loginSchema,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: usuarioApiLoginUsuarioResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as usuarioApiLoginUsuarioResponse
}
  


/**
 * @summary Logout Usuario
 */
export type usuarioApiLogoutUsuarioResponse200 = {
  data: void
  status: 200
}

export type usuarioApiLogoutUsuarioResponseSuccess = (usuarioApiLogoutUsuarioResponse200) & {
  headers: Headers;
};
;

export type usuarioApiLogoutUsuarioResponse = (usuarioApiLogoutUsuarioResponseSuccess)

export const getUsuarioApiLogoutUsuarioUrl = () => {


  

  return `/api/usuarios/logout`
}

export const usuarioApiLogoutUsuario = async ( options?: RequestInit): Promise<usuarioApiLogoutUsuarioResponse> => {
  
  const res = await fetch(getUsuarioApiLogoutUsuarioUrl(),
  {      
    ...options,
    method: 'POST'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: usuarioApiLogoutUsuarioResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as usuarioApiLogoutUsuarioResponse
}
  


/**
 * @summary List Usuarios
 */
export type usuarioApiListUsuariosResponse200 = {
  data: PagedUsuarioSchema
  status: 200
}

export type usuarioApiListUsuariosResponseSuccess = (usuarioApiListUsuariosResponse200) & {
  headers: Headers;
};
;

export type usuarioApiListUsuariosResponse = (usuarioApiListUsuariosResponseSuccess)

export const getUsuarioApiListUsuariosUrl = (params?: UsuarioApiListUsuariosParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/usuarios/listar_todos?${stringifiedParams}` : `/api/usuarios/listar_todos`
}

export const usuarioApiListUsuarios = async (params?: UsuarioApiListUsuariosParams, options?: RequestInit): Promise<usuarioApiListUsuariosResponse> => {
  
  const res = await fetch(getUsuarioApiListUsuariosUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: usuarioApiListUsuariosResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as usuarioApiListUsuariosResponse
}
  


/**
 * @summary Get Usuario
 */
export type usuarioApiGetUsuarioResponse200 = {
  data: UsuarioSchema
  status: 200
}

export type usuarioApiGetUsuarioResponseSuccess = (usuarioApiGetUsuarioResponse200) & {
  headers: Headers;
};
;

export type usuarioApiGetUsuarioResponse = (usuarioApiGetUsuarioResponseSuccess)

export const getUsuarioApiGetUsuarioUrl = (usuarioId: number,) => {


  

  return `/api/usuarios/obtener/${usuarioId}`
}

export const usuarioApiGetUsuario = async (usuarioId: number, options?: RequestInit): Promise<usuarioApiGetUsuarioResponse> => {
  
  const res = await fetch(getUsuarioApiGetUsuarioUrl(usuarioId),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: usuarioApiGetUsuarioResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as usuarioApiGetUsuarioResponse
}
  


/**
 * @summary Create Usuario
 */
export type usuarioApiCreateUsuarioResponse200 = {
  data: UsuarioSchema
  status: 200
}

export type usuarioApiCreateUsuarioResponseSuccess = (usuarioApiCreateUsuarioResponse200) & {
  headers: Headers;
};
;

export type usuarioApiCreateUsuarioResponse = (usuarioApiCreateUsuarioResponseSuccess)

export const getUsuarioApiCreateUsuarioUrl = () => {


  

  return `/api/usuarios/crear`
}

export const usuarioApiCreateUsuario = async (usuarioCreateSchema: UsuarioCreateSchema, options?: RequestInit): Promise<usuarioApiCreateUsuarioResponse> => {
  
  const res = await fetch(getUsuarioApiCreateUsuarioUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      usuarioCreateSchema,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: usuarioApiCreateUsuarioResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as usuarioApiCreateUsuarioResponse
}
  


/**
 * @summary Update Usuario
 */
export type usuarioApiUpdateUsuarioResponse200 = {
  data: UsuarioSchema
  status: 200
}

export type usuarioApiUpdateUsuarioResponseSuccess = (usuarioApiUpdateUsuarioResponse200) & {
  headers: Headers;
};
;

export type usuarioApiUpdateUsuarioResponse = (usuarioApiUpdateUsuarioResponseSuccess)

export const getUsuarioApiUpdateUsuarioUrl = (usuarioId: number,) => {


  

  return `/api/usuarios/actualizar/${usuarioId}`
}

export const usuarioApiUpdateUsuario = async (usuarioId: number,
    usuarioUpdateSchema: UsuarioUpdateSchema, options?: RequestInit): Promise<usuarioApiUpdateUsuarioResponse> => {
  
  const res = await fetch(getUsuarioApiUpdateUsuarioUrl(usuarioId),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      usuarioUpdateSchema,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: usuarioApiUpdateUsuarioResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as usuarioApiUpdateUsuarioResponse
}
  


/**
 * @summary Delete Usuario
 */
export type usuarioApiDeleteUsuarioResponse200 = {
  data: void
  status: 200
}

export type usuarioApiDeleteUsuarioResponseSuccess = (usuarioApiDeleteUsuarioResponse200) & {
  headers: Headers;
};
;

export type usuarioApiDeleteUsuarioResponse = (usuarioApiDeleteUsuarioResponseSuccess)

export const getUsuarioApiDeleteUsuarioUrl = (usuarioId: number,) => {


  

  return `/api/usuarios/eliminar/${usuarioId}`
}

export const usuarioApiDeleteUsuario = async (usuarioId: number, options?: RequestInit): Promise<usuarioApiDeleteUsuarioResponse> => {
  
  const res = await fetch(getUsuarioApiDeleteUsuarioUrl(usuarioId),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: usuarioApiDeleteUsuarioResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as usuarioApiDeleteUsuarioResponse
}
  


/**
 * @summary List Proveedores
 */
export type proveedorApiListProveedoresResponse200 = {
  data: PagedProveedorSchema
  status: 200
}

export type proveedorApiListProveedoresResponseSuccess = (proveedorApiListProveedoresResponse200) & {
  headers: Headers;
};
;

export type proveedorApiListProveedoresResponse = (proveedorApiListProveedoresResponseSuccess)

export const getProveedorApiListProveedoresUrl = (params?: ProveedorApiListProveedoresParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/proveedores/listar_todos?${stringifiedParams}` : `/api/proveedores/listar_todos`
}

export const proveedorApiListProveedores = async (params?: ProveedorApiListProveedoresParams, options?: RequestInit): Promise<proveedorApiListProveedoresResponse> => {
  
  const res = await fetch(getProveedorApiListProveedoresUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: proveedorApiListProveedoresResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as proveedorApiListProveedoresResponse
}
  


/**
 * @summary Get Proveedor
 */
export type proveedorApiGetProveedorResponse200 = {
  data: ProveedorSchema
  status: 200
}

export type proveedorApiGetProveedorResponseSuccess = (proveedorApiGetProveedorResponse200) & {
  headers: Headers;
};
;

export type proveedorApiGetProveedorResponse = (proveedorApiGetProveedorResponseSuccess)

export const getProveedorApiGetProveedorUrl = (proveedorId: number,) => {


  

  return `/api/proveedores/obtener/${proveedorId}`
}

export const proveedorApiGetProveedor = async (proveedorId: number, options?: RequestInit): Promise<proveedorApiGetProveedorResponse> => {
  
  const res = await fetch(getProveedorApiGetProveedorUrl(proveedorId),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: proveedorApiGetProveedorResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as proveedorApiGetProveedorResponse
}
  


/**
 * @summary Create Proveedor
 */
export type proveedorApiCreateProveedorResponse200 = {
  data: ProveedorSchema
  status: 200
}

export type proveedorApiCreateProveedorResponseSuccess = (proveedorApiCreateProveedorResponse200) & {
  headers: Headers;
};
;

export type proveedorApiCreateProveedorResponse = (proveedorApiCreateProveedorResponseSuccess)

export const getProveedorApiCreateProveedorUrl = () => {


  

  return `/api/proveedores/crear`
}

export const proveedorApiCreateProveedor = async (proveedorCreateSchema: ProveedorCreateSchema, options?: RequestInit): Promise<proveedorApiCreateProveedorResponse> => {
  
  const res = await fetch(getProveedorApiCreateProveedorUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      proveedorCreateSchema,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: proveedorApiCreateProveedorResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as proveedorApiCreateProveedorResponse
}
  


/**
 * @summary Update Proveedor
 */
export type proveedorApiUpdateProveedorResponse200 = {
  data: ProveedorSchema
  status: 200
}

export type proveedorApiUpdateProveedorResponseSuccess = (proveedorApiUpdateProveedorResponse200) & {
  headers: Headers;
};
;

export type proveedorApiUpdateProveedorResponse = (proveedorApiUpdateProveedorResponseSuccess)

export const getProveedorApiUpdateProveedorUrl = (proveedorId: number,) => {


  

  return `/api/proveedores/actualizar/${proveedorId}`
}

export const proveedorApiUpdateProveedor = async (proveedorId: number,
    proveedorUpdateSchema: ProveedorUpdateSchema, options?: RequestInit): Promise<proveedorApiUpdateProveedorResponse> => {
  
  const res = await fetch(getProveedorApiUpdateProveedorUrl(proveedorId),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      proveedorUpdateSchema,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: proveedorApiUpdateProveedorResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as proveedorApiUpdateProveedorResponse
}
  


/**
 * @summary Delete Proveedor
 */
export type proveedorApiDeleteProveedorResponse200 = {
  data: void
  status: 200
}

export type proveedorApiDeleteProveedorResponseSuccess = (proveedorApiDeleteProveedorResponse200) & {
  headers: Headers;
};
;

export type proveedorApiDeleteProveedorResponse = (proveedorApiDeleteProveedorResponseSuccess)

export const getProveedorApiDeleteProveedorUrl = (proveedorId: number,) => {


  

  return `/api/proveedores/eliminar/${proveedorId}`
}

export const proveedorApiDeleteProveedor = async (proveedorId: number, options?: RequestInit): Promise<proveedorApiDeleteProveedorResponse> => {
  
  const res = await fetch(getProveedorApiDeleteProveedorUrl(proveedorId),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: proveedorApiDeleteProveedorResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as proveedorApiDeleteProveedorResponse
}
  


/**
 * @summary List Proveedor Usuarios
 */
export type proveedorApiListProveedorUsuariosResponse200 = {
  data: PagedProveedorUsuarioSchema
  status: 200
}

export type proveedorApiListProveedorUsuariosResponseSuccess = (proveedorApiListProveedorUsuariosResponse200) & {
  headers: Headers;
};
;

export type proveedorApiListProveedorUsuariosResponse = (proveedorApiListProveedorUsuariosResponseSuccess)

export const getProveedorApiListProveedorUsuariosUrl = (params?: ProveedorApiListProveedorUsuariosParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/proveedores/usuarios/listar_todos?${stringifiedParams}` : `/api/proveedores/usuarios/listar_todos`
}

export const proveedorApiListProveedorUsuarios = async (params?: ProveedorApiListProveedorUsuariosParams, options?: RequestInit): Promise<proveedorApiListProveedorUsuariosResponse> => {
  
  const res = await fetch(getProveedorApiListProveedorUsuariosUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: proveedorApiListProveedorUsuariosResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as proveedorApiListProveedorUsuariosResponse
}
  


/**
 * @summary Create Proveedor Usuario
 */
export type proveedorApiCreateProveedorUsuarioResponse200 = {
  data: ProveedorUsuarioSchema
  status: 200
}

export type proveedorApiCreateProveedorUsuarioResponseSuccess = (proveedorApiCreateProveedorUsuarioResponse200) & {
  headers: Headers;
};
;

export type proveedorApiCreateProveedorUsuarioResponse = (proveedorApiCreateProveedorUsuarioResponseSuccess)

export const getProveedorApiCreateProveedorUsuarioUrl = () => {


  

  return `/api/proveedores/usuarios/crear`
}

export const proveedorApiCreateProveedorUsuario = async (proveedorUsuarioCreateSchema: ProveedorUsuarioCreateSchema, options?: RequestInit): Promise<proveedorApiCreateProveedorUsuarioResponse> => {
  
  const res = await fetch(getProveedorApiCreateProveedorUsuarioUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      proveedorUsuarioCreateSchema,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: proveedorApiCreateProveedorUsuarioResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as proveedorApiCreateProveedorUsuarioResponse
}
  


/**
 * @summary Update Proveedor Usuario
 */
export type proveedorApiUpdateProveedorUsuarioResponse200 = {
  data: ProveedorUsuarioSchema
  status: 200
}

export type proveedorApiUpdateProveedorUsuarioResponseSuccess = (proveedorApiUpdateProveedorUsuarioResponse200) & {
  headers: Headers;
};
;

export type proveedorApiUpdateProveedorUsuarioResponse = (proveedorApiUpdateProveedorUsuarioResponseSuccess)

export const getProveedorApiUpdateProveedorUsuarioUrl = (relacionId: number,) => {


  

  return `/api/proveedores/usuarios/actualizar/${relacionId}`
}

export const proveedorApiUpdateProveedorUsuario = async (relacionId: number,
    proveedorUsuarioUpdateSchema: ProveedorUsuarioUpdateSchema, options?: RequestInit): Promise<proveedorApiUpdateProveedorUsuarioResponse> => {
  
  const res = await fetch(getProveedorApiUpdateProveedorUsuarioUrl(relacionId),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      proveedorUsuarioUpdateSchema,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: proveedorApiUpdateProveedorUsuarioResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as proveedorApiUpdateProveedorUsuarioResponse
}
  


/**
 * @summary Delete Proveedor Usuario
 */
export type proveedorApiDeleteProveedorUsuarioResponse200 = {
  data: void
  status: 200
}

export type proveedorApiDeleteProveedorUsuarioResponseSuccess = (proveedorApiDeleteProveedorUsuarioResponse200) & {
  headers: Headers;
};
;

export type proveedorApiDeleteProveedorUsuarioResponse = (proveedorApiDeleteProveedorUsuarioResponseSuccess)

export const getProveedorApiDeleteProveedorUsuarioUrl = (relacionId: number,) => {


  

  return `/api/proveedores/usuarios/eliminar/${relacionId}`
}

export const proveedorApiDeleteProveedorUsuario = async (relacionId: number, options?: RequestInit): Promise<proveedorApiDeleteProveedorUsuarioResponse> => {
  
  const res = await fetch(getProveedorApiDeleteProveedorUsuarioUrl(relacionId),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: proveedorApiDeleteProveedorUsuarioResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as proveedorApiDeleteProveedorUsuarioResponse
}
  


/**
 * @summary List Productos
 */
export type productoApiListProductosResponse200 = {
  data: PagedProductoSchema
  status: 200
}

export type productoApiListProductosResponseSuccess = (productoApiListProductosResponse200) & {
  headers: Headers;
};
;

export type productoApiListProductosResponse = (productoApiListProductosResponseSuccess)

export const getProductoApiListProductosUrl = (params?: ProductoApiListProductosParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/productos/listar_todos?${stringifiedParams}` : `/api/productos/listar_todos`
}

export const productoApiListProductos = async (params?: ProductoApiListProductosParams, options?: RequestInit): Promise<productoApiListProductosResponse> => {
  
  const res = await fetch(getProductoApiListProductosUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: productoApiListProductosResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as productoApiListProductosResponse
}
  


/**
 * @summary Get Producto
 */
export type productoApiGetProductoResponse200 = {
  data: ProductoSchema
  status: 200
}

export type productoApiGetProductoResponseSuccess = (productoApiGetProductoResponse200) & {
  headers: Headers;
};
;

export type productoApiGetProductoResponse = (productoApiGetProductoResponseSuccess)

export const getProductoApiGetProductoUrl = (productoId: number,) => {


  

  return `/api/productos/obtener/${productoId}`
}

export const productoApiGetProducto = async (productoId: number, options?: RequestInit): Promise<productoApiGetProductoResponse> => {
  
  const res = await fetch(getProductoApiGetProductoUrl(productoId),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: productoApiGetProductoResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as productoApiGetProductoResponse
}
  


/**
 * @summary Create Producto
 */
export type productoApiCreateProductoResponse200 = {
  data: ProductoSchema
  status: 200
}

export type productoApiCreateProductoResponseSuccess = (productoApiCreateProductoResponse200) & {
  headers: Headers;
};
;

export type productoApiCreateProductoResponse = (productoApiCreateProductoResponseSuccess)

export const getProductoApiCreateProductoUrl = () => {


  

  return `/api/productos/crear`
}

export const productoApiCreateProducto = async (productoApiCreateProductoBody: ProductoApiCreateProductoBody, options?: RequestInit): Promise<productoApiCreateProductoResponse> => {
    const formData = new FormData();
if(productoApiCreateProductoBody.imagen !== undefined) {
 formData.append(`imagen`, productoApiCreateProductoBody.imagen);
 }
formData.append(`data`, JSON.stringify(productoApiCreateProductoBody.data));

  const res = await fetch(getProductoApiCreateProductoUrl(),
  {      
    ...options,
    method: 'POST'
    ,
    body: 
      formData,
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: productoApiCreateProductoResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as productoApiCreateProductoResponse
}
  


/**
 * @summary Update Producto
 */
export type productoApiUpdateProductoResponse200 = {
  data: ProductoSchema
  status: 200
}

export type productoApiUpdateProductoResponseSuccess = (productoApiUpdateProductoResponse200) & {
  headers: Headers;
};
;

export type productoApiUpdateProductoResponse = (productoApiUpdateProductoResponseSuccess)

export const getProductoApiUpdateProductoUrl = (productoId: number,) => {


  

  return `/api/productos/actualizar/${productoId}`
}

export const productoApiUpdateProducto = async (productoId: number,
    productoApiUpdateProductoBody: ProductoApiUpdateProductoBody, options?: RequestInit): Promise<productoApiUpdateProductoResponse> => {
    const formData = new FormData();
if(productoApiUpdateProductoBody.imagen !== undefined) {
 formData.append(`imagen`, productoApiUpdateProductoBody.imagen);
 }
formData.append(`data`, JSON.stringify(productoApiUpdateProductoBody.data));

  const res = await fetch(getProductoApiUpdateProductoUrl(productoId),
  {      
    ...options,
    method: 'PATCH'
    ,
    body: 
      formData,
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: productoApiUpdateProductoResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as productoApiUpdateProductoResponse
}
  


/**
 * @summary Delete Producto
 */
export type productoApiDeleteProductoResponse200 = {
  data: void
  status: 200
}

export type productoApiDeleteProductoResponseSuccess = (productoApiDeleteProductoResponse200) & {
  headers: Headers;
};
;

export type productoApiDeleteProductoResponse = (productoApiDeleteProductoResponseSuccess)

export const getProductoApiDeleteProductoUrl = (productoId: number,) => {


  

  return `/api/productos/eliminar/${productoId}`
}

export const productoApiDeleteProducto = async (productoId: number, options?: RequestInit): Promise<productoApiDeleteProductoResponse> => {
  
  const res = await fetch(getProductoApiDeleteProductoUrl(productoId),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: productoApiDeleteProductoResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as productoApiDeleteProductoResponse
}
  


/**
 * @summary List Inventario
 */
export type productoApiListInventarioResponse200 = {
  data: PagedProductoSucursalSchema
  status: 200
}

export type productoApiListInventarioResponseSuccess = (productoApiListInventarioResponse200) & {
  headers: Headers;
};
;

export type productoApiListInventarioResponse = (productoApiListInventarioResponseSuccess)

export const getProductoApiListInventarioUrl = (params?: ProductoApiListInventarioParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/productos/inventario/listar_todos?${stringifiedParams}` : `/api/productos/inventario/listar_todos`
}

export const productoApiListInventario = async (params?: ProductoApiListInventarioParams, options?: RequestInit): Promise<productoApiListInventarioResponse> => {
  
  const res = await fetch(getProductoApiListInventarioUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: productoApiListInventarioResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as productoApiListInventarioResponse
}
  


/**
 * @summary Create Inventario
 */
export type productoApiCreateInventarioResponse200 = {
  data: ProductoSucursalSchema
  status: 200
}

export type productoApiCreateInventarioResponseSuccess = (productoApiCreateInventarioResponse200) & {
  headers: Headers;
};
;

export type productoApiCreateInventarioResponse = (productoApiCreateInventarioResponseSuccess)

export const getProductoApiCreateInventarioUrl = () => {


  

  return `/api/productos/inventario/crear`
}

export const productoApiCreateInventario = async (productoSucursalCreateSchema: ProductoSucursalCreateSchema, options?: RequestInit): Promise<productoApiCreateInventarioResponse> => {
  
  const res = await fetch(getProductoApiCreateInventarioUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      productoSucursalCreateSchema,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: productoApiCreateInventarioResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as productoApiCreateInventarioResponse
}
  


/**
 * @summary Update Inventario
 */
export type productoApiUpdateInventarioResponse200 = {
  data: ProductoSucursalSchema
  status: 200
}

export type productoApiUpdateInventarioResponseSuccess = (productoApiUpdateInventarioResponse200) & {
  headers: Headers;
};
;

export type productoApiUpdateInventarioResponse = (productoApiUpdateInventarioResponseSuccess)

export const getProductoApiUpdateInventarioUrl = (inventarioId: number,) => {


  

  return `/api/productos/inventario/actualizar/${inventarioId}`
}

export const productoApiUpdateInventario = async (inventarioId: number,
    productoSucursalUpdateSchema: ProductoSucursalUpdateSchema, options?: RequestInit): Promise<productoApiUpdateInventarioResponse> => {
  
  const res = await fetch(getProductoApiUpdateInventarioUrl(inventarioId),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      productoSucursalUpdateSchema,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: productoApiUpdateInventarioResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as productoApiUpdateInventarioResponse
}
  


/**
 * @summary Delete Inventario
 */
export type productoApiDeleteInventarioResponse200 = {
  data: void
  status: 200
}

export type productoApiDeleteInventarioResponseSuccess = (productoApiDeleteInventarioResponse200) & {
  headers: Headers;
};
;

export type productoApiDeleteInventarioResponse = (productoApiDeleteInventarioResponseSuccess)

export const getProductoApiDeleteInventarioUrl = (inventarioId: number,) => {


  

  return `/api/productos/inventario/eliminar/${inventarioId}`
}

export const productoApiDeleteInventario = async (inventarioId: number, options?: RequestInit): Promise<productoApiDeleteInventarioResponse> => {
  
  const res = await fetch(getProductoApiDeleteInventarioUrl(inventarioId),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: productoApiDeleteInventarioResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as productoApiDeleteInventarioResponse
}
  


/**
 * @summary List Sucursales
 */
export type sucursalApiListSucursalesResponse200 = {
  data: PagedSucursalSchema
  status: 200
}

export type sucursalApiListSucursalesResponseSuccess = (sucursalApiListSucursalesResponse200) & {
  headers: Headers;
};
;

export type sucursalApiListSucursalesResponse = (sucursalApiListSucursalesResponseSuccess)

export const getSucursalApiListSucursalesUrl = (params?: SucursalApiListSucursalesParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/sucursales/listar_todos?${stringifiedParams}` : `/api/sucursales/listar_todos`
}

export const sucursalApiListSucursales = async (params?: SucursalApiListSucursalesParams, options?: RequestInit): Promise<sucursalApiListSucursalesResponse> => {
  
  const res = await fetch(getSucursalApiListSucursalesUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: sucursalApiListSucursalesResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as sucursalApiListSucursalesResponse
}
  


/**
 * @summary Get Sucursal
 */
export type sucursalApiGetSucursalResponse200 = {
  data: SucursalSchema
  status: 200
}

export type sucursalApiGetSucursalResponseSuccess = (sucursalApiGetSucursalResponse200) & {
  headers: Headers;
};
;

export type sucursalApiGetSucursalResponse = (sucursalApiGetSucursalResponseSuccess)

export const getSucursalApiGetSucursalUrl = (sucursalId: number,) => {


  

  return `/api/sucursales/obtener/${sucursalId}`
}

export const sucursalApiGetSucursal = async (sucursalId: number, options?: RequestInit): Promise<sucursalApiGetSucursalResponse> => {
  
  const res = await fetch(getSucursalApiGetSucursalUrl(sucursalId),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: sucursalApiGetSucursalResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as sucursalApiGetSucursalResponse
}
  


/**
 * @summary Create Sucursal
 */
export type sucursalApiCreateSucursalResponse200 = {
  data: SucursalSchema
  status: 200
}

export type sucursalApiCreateSucursalResponseSuccess = (sucursalApiCreateSucursalResponse200) & {
  headers: Headers;
};
;

export type sucursalApiCreateSucursalResponse = (sucursalApiCreateSucursalResponseSuccess)

export const getSucursalApiCreateSucursalUrl = () => {


  

  return `/api/sucursales/crear`
}

export const sucursalApiCreateSucursal = async (sucursalCreateSchema: SucursalCreateSchema, options?: RequestInit): Promise<sucursalApiCreateSucursalResponse> => {
  
  const res = await fetch(getSucursalApiCreateSucursalUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      sucursalCreateSchema,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: sucursalApiCreateSucursalResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as sucursalApiCreateSucursalResponse
}
  


/**
 * @summary Update Sucursal
 */
export type sucursalApiUpdateSucursalResponse200 = {
  data: SucursalSchema
  status: 200
}

export type sucursalApiUpdateSucursalResponseSuccess = (sucursalApiUpdateSucursalResponse200) & {
  headers: Headers;
};
;

export type sucursalApiUpdateSucursalResponse = (sucursalApiUpdateSucursalResponseSuccess)

export const getSucursalApiUpdateSucursalUrl = (sucursalId: number,) => {


  

  return `/api/sucursales/actualizar/${sucursalId}`
}

export const sucursalApiUpdateSucursal = async (sucursalId: number,
    sucursalUpdateSchema: SucursalUpdateSchema, options?: RequestInit): Promise<sucursalApiUpdateSucursalResponse> => {
  
  const res = await fetch(getSucursalApiUpdateSucursalUrl(sucursalId),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      sucursalUpdateSchema,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: sucursalApiUpdateSucursalResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as sucursalApiUpdateSucursalResponse
}
  


/**
 * @summary Delete Sucursal
 */
export type sucursalApiDeleteSucursalResponse200 = {
  data: void
  status: 200
}

export type sucursalApiDeleteSucursalResponseSuccess = (sucursalApiDeleteSucursalResponse200) & {
  headers: Headers;
};
;

export type sucursalApiDeleteSucursalResponse = (sucursalApiDeleteSucursalResponseSuccess)

export const getSucursalApiDeleteSucursalUrl = (sucursalId: number,) => {


  

  return `/api/sucursales/eliminar/${sucursalId}`
}

export const sucursalApiDeleteSucursal = async (sucursalId: number, options?: RequestInit): Promise<sucursalApiDeleteSucursalResponse> => {
  
  const res = await fetch(getSucursalApiDeleteSucursalUrl(sucursalId),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: sucursalApiDeleteSucursalResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as sucursalApiDeleteSucursalResponse
}
  


/**
 * @summary List Sucursal Usuarios
 */
export type sucursalApiListSucursalUsuariosResponse200 = {
  data: PagedSucursalUsuarioSchema
  status: 200
}

export type sucursalApiListSucursalUsuariosResponseSuccess = (sucursalApiListSucursalUsuariosResponse200) & {
  headers: Headers;
};
;

export type sucursalApiListSucursalUsuariosResponse = (sucursalApiListSucursalUsuariosResponseSuccess)

export const getSucursalApiListSucursalUsuariosUrl = (params?: SucursalApiListSucursalUsuariosParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/sucursales/usuarios/listar_todos?${stringifiedParams}` : `/api/sucursales/usuarios/listar_todos`
}

export const sucursalApiListSucursalUsuarios = async (params?: SucursalApiListSucursalUsuariosParams, options?: RequestInit): Promise<sucursalApiListSucursalUsuariosResponse> => {
  
  const res = await fetch(getSucursalApiListSucursalUsuariosUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: sucursalApiListSucursalUsuariosResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as sucursalApiListSucursalUsuariosResponse
}
  


/**
 * @summary Create Sucursal Usuario
 */
export type sucursalApiCreateSucursalUsuarioResponse200 = {
  data: SucursalUsuarioSchema
  status: 200
}

export type sucursalApiCreateSucursalUsuarioResponseSuccess = (sucursalApiCreateSucursalUsuarioResponse200) & {
  headers: Headers;
};
;

export type sucursalApiCreateSucursalUsuarioResponse = (sucursalApiCreateSucursalUsuarioResponseSuccess)

export const getSucursalApiCreateSucursalUsuarioUrl = () => {


  

  return `/api/sucursales/usuarios/crear`
}

export const sucursalApiCreateSucursalUsuario = async (sucursalUsuarioCreateSchema: SucursalUsuarioCreateSchema, options?: RequestInit): Promise<sucursalApiCreateSucursalUsuarioResponse> => {
  
  const res = await fetch(getSucursalApiCreateSucursalUsuarioUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      sucursalUsuarioCreateSchema,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: sucursalApiCreateSucursalUsuarioResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as sucursalApiCreateSucursalUsuarioResponse
}
  


/**
 * @summary Update Sucursal Usuario
 */
export type sucursalApiUpdateSucursalUsuarioResponse200 = {
  data: SucursalUsuarioSchema
  status: 200
}

export type sucursalApiUpdateSucursalUsuarioResponseSuccess = (sucursalApiUpdateSucursalUsuarioResponse200) & {
  headers: Headers;
};
;

export type sucursalApiUpdateSucursalUsuarioResponse = (sucursalApiUpdateSucursalUsuarioResponseSuccess)

export const getSucursalApiUpdateSucursalUsuarioUrl = (relacionId: number,) => {


  

  return `/api/sucursales/usuarios/actualizar/${relacionId}`
}

export const sucursalApiUpdateSucursalUsuario = async (relacionId: number,
    sucursalUsuarioUpdateSchema: SucursalUsuarioUpdateSchema, options?: RequestInit): Promise<sucursalApiUpdateSucursalUsuarioResponse> => {
  
  const res = await fetch(getSucursalApiUpdateSucursalUsuarioUrl(relacionId),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      sucursalUsuarioUpdateSchema,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: sucursalApiUpdateSucursalUsuarioResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as sucursalApiUpdateSucursalUsuarioResponse
}
  


/**
 * @summary Delete Sucursal Usuario
 */
export type sucursalApiDeleteSucursalUsuarioResponse200 = {
  data: void
  status: 200
}

export type sucursalApiDeleteSucursalUsuarioResponseSuccess = (sucursalApiDeleteSucursalUsuarioResponse200) & {
  headers: Headers;
};
;

export type sucursalApiDeleteSucursalUsuarioResponse = (sucursalApiDeleteSucursalUsuarioResponseSuccess)

export const getSucursalApiDeleteSucursalUsuarioUrl = (relacionId: number,) => {


  

  return `/api/sucursales/usuarios/eliminar/${relacionId}`
}

export const sucursalApiDeleteSucursalUsuario = async (relacionId: number, options?: RequestInit): Promise<sucursalApiDeleteSucursalUsuarioResponse> => {
  
  const res = await fetch(getSucursalApiDeleteSucursalUsuarioUrl(relacionId),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: sucursalApiDeleteSucursalUsuarioResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as sucursalApiDeleteSucursalUsuarioResponse
}
  


/**
 * @summary List Pedidos
 */
export type pedidoApiListPedidosResponse200 = {
  data: PagedPedidoSchema
  status: 200
}

export type pedidoApiListPedidosResponseSuccess = (pedidoApiListPedidosResponse200) & {
  headers: Headers;
};
;

export type pedidoApiListPedidosResponse = (pedidoApiListPedidosResponseSuccess)

export const getPedidoApiListPedidosUrl = (params?: PedidoApiListPedidosParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/pedidos/listar_todos?${stringifiedParams}` : `/api/pedidos/listar_todos`
}

export const pedidoApiListPedidos = async (params?: PedidoApiListPedidosParams, options?: RequestInit): Promise<pedidoApiListPedidosResponse> => {
  
  const res = await fetch(getPedidoApiListPedidosUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: pedidoApiListPedidosResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as pedidoApiListPedidosResponse
}
  


/**
 * @summary Get Pedido
 */
export type pedidoApiGetPedidoResponse200 = {
  data: PedidoSchema
  status: 200
}

export type pedidoApiGetPedidoResponseSuccess = (pedidoApiGetPedidoResponse200) & {
  headers: Headers;
};
;

export type pedidoApiGetPedidoResponse = (pedidoApiGetPedidoResponseSuccess)

export const getPedidoApiGetPedidoUrl = (pedidoId: number,) => {


  

  return `/api/pedidos/obtener/${pedidoId}`
}

export const pedidoApiGetPedido = async (pedidoId: number, options?: RequestInit): Promise<pedidoApiGetPedidoResponse> => {
  
  const res = await fetch(getPedidoApiGetPedidoUrl(pedidoId),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: pedidoApiGetPedidoResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as pedidoApiGetPedidoResponse
}
  


/**
 * @summary Create Pedido
 */
export type pedidoApiCreatePedidoResponse200 = {
  data: PedidoSchema
  status: 200
}

export type pedidoApiCreatePedidoResponseSuccess = (pedidoApiCreatePedidoResponse200) & {
  headers: Headers;
};
;

export type pedidoApiCreatePedidoResponse = (pedidoApiCreatePedidoResponseSuccess)

export const getPedidoApiCreatePedidoUrl = () => {


  

  return `/api/pedidos/crear`
}

export const pedidoApiCreatePedido = async (pedidoCreateSchema: PedidoCreateSchema, options?: RequestInit): Promise<pedidoApiCreatePedidoResponse> => {
  
  const res = await fetch(getPedidoApiCreatePedidoUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      pedidoCreateSchema,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: pedidoApiCreatePedidoResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as pedidoApiCreatePedidoResponse
}
  


/**
 * @summary Update Pedido
 */
export type pedidoApiUpdatePedidoResponse200 = {
  data: PedidoSchema
  status: 200
}

export type pedidoApiUpdatePedidoResponseSuccess = (pedidoApiUpdatePedidoResponse200) & {
  headers: Headers;
};
;

export type pedidoApiUpdatePedidoResponse = (pedidoApiUpdatePedidoResponseSuccess)

export const getPedidoApiUpdatePedidoUrl = (pedidoId: number,) => {


  

  return `/api/pedidos/actualizar/${pedidoId}`
}

export const pedidoApiUpdatePedido = async (pedidoId: number,
    pedidoUpdateSchema: PedidoUpdateSchema, options?: RequestInit): Promise<pedidoApiUpdatePedidoResponse> => {
  
  const res = await fetch(getPedidoApiUpdatePedidoUrl(pedidoId),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      pedidoUpdateSchema,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: pedidoApiUpdatePedidoResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as pedidoApiUpdatePedidoResponse
}
  


/**
 * @summary Delete Pedido
 */
export type pedidoApiDeletePedidoResponse200 = {
  data: void
  status: 200
}

export type pedidoApiDeletePedidoResponseSuccess = (pedidoApiDeletePedidoResponse200) & {
  headers: Headers;
};
;

export type pedidoApiDeletePedidoResponse = (pedidoApiDeletePedidoResponseSuccess)

export const getPedidoApiDeletePedidoUrl = (pedidoId: number,) => {


  

  return `/api/pedidos/eliminar/${pedidoId}`
}

export const pedidoApiDeletePedido = async (pedidoId: number, options?: RequestInit): Promise<pedidoApiDeletePedidoResponse> => {
  
  const res = await fetch(getPedidoApiDeletePedidoUrl(pedidoId),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: pedidoApiDeletePedidoResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as pedidoApiDeletePedidoResponse
}
  


/**
 * @summary List Detalles
 */
export type pedidoApiListDetallesResponse200 = {
  data: PagedDetallePedidoSchema
  status: 200
}

export type pedidoApiListDetallesResponseSuccess = (pedidoApiListDetallesResponse200) & {
  headers: Headers;
};
;

export type pedidoApiListDetallesResponse = (pedidoApiListDetallesResponseSuccess)

export const getPedidoApiListDetallesUrl = (params?: PedidoApiListDetallesParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/pedidos/detalles/listar_todos?${stringifiedParams}` : `/api/pedidos/detalles/listar_todos`
}

export const pedidoApiListDetalles = async (params?: PedidoApiListDetallesParams, options?: RequestInit): Promise<pedidoApiListDetallesResponse> => {
  
  const res = await fetch(getPedidoApiListDetallesUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: pedidoApiListDetallesResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as pedidoApiListDetallesResponse
}
  


/**
 * @summary Create Detalle
 */
export type pedidoApiCreateDetalleResponse200 = {
  data: DetallePedidoSchema
  status: 200
}

export type pedidoApiCreateDetalleResponseSuccess = (pedidoApiCreateDetalleResponse200) & {
  headers: Headers;
};
;

export type pedidoApiCreateDetalleResponse = (pedidoApiCreateDetalleResponseSuccess)

export const getPedidoApiCreateDetalleUrl = () => {


  

  return `/api/pedidos/detalles/crear`
}

export const pedidoApiCreateDetalle = async (detallePedidoCreateSchema: DetallePedidoCreateSchema, options?: RequestInit): Promise<pedidoApiCreateDetalleResponse> => {
  
  const res = await fetch(getPedidoApiCreateDetalleUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      detallePedidoCreateSchema,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: pedidoApiCreateDetalleResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as pedidoApiCreateDetalleResponse
}
  


/**
 * @summary Update Detalle
 */
export type pedidoApiUpdateDetalleResponse200 = {
  data: DetallePedidoSchema
  status: 200
}

export type pedidoApiUpdateDetalleResponseSuccess = (pedidoApiUpdateDetalleResponse200) & {
  headers: Headers;
};
;

export type pedidoApiUpdateDetalleResponse = (pedidoApiUpdateDetalleResponseSuccess)

export const getPedidoApiUpdateDetalleUrl = (detalleId: number,) => {


  

  return `/api/pedidos/detalles/actualizar/${detalleId}`
}

export const pedidoApiUpdateDetalle = async (detalleId: number,
    detallePedidoUpdateSchema: DetallePedidoUpdateSchema, options?: RequestInit): Promise<pedidoApiUpdateDetalleResponse> => {
  
  const res = await fetch(getPedidoApiUpdateDetalleUrl(detalleId),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      detallePedidoUpdateSchema,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: pedidoApiUpdateDetalleResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as pedidoApiUpdateDetalleResponse
}
  


/**
 * @summary Delete Detalle
 */
export type pedidoApiDeleteDetalleResponse200 = {
  data: void
  status: 200
}

export type pedidoApiDeleteDetalleResponseSuccess = (pedidoApiDeleteDetalleResponse200) & {
  headers: Headers;
};
;

export type pedidoApiDeleteDetalleResponse = (pedidoApiDeleteDetalleResponseSuccess)

export const getPedidoApiDeleteDetalleUrl = (detalleId: number,) => {


  

  return `/api/pedidos/detalles/eliminar/${detalleId}`
}

export const pedidoApiDeleteDetalle = async (detalleId: number, options?: RequestInit): Promise<pedidoApiDeleteDetalleResponse> => {
  
  const res = await fetch(getPedidoApiDeleteDetalleUrl(detalleId),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: pedidoApiDeleteDetalleResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as pedidoApiDeleteDetalleResponse
}
