/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * Almacen API
 * OpenAPI spec version: 1.0.0
 */
import type {
  CambiarMiContrasena,
  DashboardEstadisticas,
  LoginRequest,
  PagedPedido,
  PagedPedidoDetalle,
  PagedPedidoProveedorResumen,
  PagedProductoList,
  PagedProveedor,
  PagedUsuario,
  Pedido,
  PedidoApiListarMisPedidosHechosParams,
  PedidoApiListarMisPedidosRecibidosParams,
  PedidoApiListarPedidosParams,
  PedidoApiListarProductosPedidoPorProveedorParams,
  PedidoApiListarProveedoresResumenPorPedidoParams,
  PedidoCambiarEstado,
  PedidoCopiaResumen,
  PedidoCreate,
  PedidoDetalle,
  PedidoDetalleCreate,
  PedidoDetalleUpdate,
  PedidoUpdate,
  ProductoApiActualizarProductoBody,
  ProductoApiCrearProductoBody,
  ProductoApiListarProductosPorProveedorParams,
  ProductoApiListarProductosTodosParams,
  ProductoDetail,
  Proveedor,
  ProveedorApiListarProveedoresParams,
  ProveedorCreate,
  ProveedorUpdate,
  TokenResponse,
  Usuario,
  UsuarioApiListarSucursalesParaPedidoParams,
  UsuarioApiListarSucursalesParams,
  UsuarioApiListarUsuariosParams,
  UsuarioCreate,
  UsuarioUpdate
} from './schemas';

/**
 * @summary Login
 */
export type usuarioApiLoginResponse200 = {
  data: TokenResponse
  status: 200
}

export type usuarioApiLoginResponseSuccess = (usuarioApiLoginResponse200) & {
  headers: Headers;
};
;

export type usuarioApiLoginResponse = (usuarioApiLoginResponseSuccess)

export const getUsuarioApiLoginUrl = () => {


  

  return `/api/usuarios/login`
}

export const usuarioApiLogin = async (loginRequest: LoginRequest, options?: RequestInit): Promise<usuarioApiLoginResponse> => {
  
  const res = await fetch(getUsuarioApiLoginUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      loginRequest,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: usuarioApiLoginResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as usuarioApiLoginResponse
}
  


/**
 * @summary Logout
 */
export type usuarioApiLogoutResponse200 = {
  data: void
  status: 200
}

export type usuarioApiLogoutResponseSuccess = (usuarioApiLogoutResponse200) & {
  headers: Headers;
};
;

export type usuarioApiLogoutResponse = (usuarioApiLogoutResponseSuccess)

export const getUsuarioApiLogoutUrl = () => {


  

  return `/api/usuarios/logout`
}

export const usuarioApiLogout = async ( options?: RequestInit): Promise<usuarioApiLogoutResponse> => {
  
  const res = await fetch(getUsuarioApiLogoutUrl(),
  {      
    ...options,
    method: 'POST'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: usuarioApiLogoutResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as usuarioApiLogoutResponse
}
  


/**
 * @summary Mi Perfil
 */
export type usuarioApiMiPerfilResponse200 = {
  data: Usuario
  status: 200
}

export type usuarioApiMiPerfilResponseSuccess = (usuarioApiMiPerfilResponse200) & {
  headers: Headers;
};
;

export type usuarioApiMiPerfilResponse = (usuarioApiMiPerfilResponseSuccess)

export const getUsuarioApiMiPerfilUrl = () => {


  

  return `/api/usuarios/mi_perfil`
}

export const usuarioApiMiPerfil = async ( options?: RequestInit): Promise<usuarioApiMiPerfilResponse> => {
  
  const res = await fetch(getUsuarioApiMiPerfilUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: usuarioApiMiPerfilResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as usuarioApiMiPerfilResponse
}
  


/**
 * Permisos: requiere rol admin.
 * @summary Listar Usuarios
 */
export type usuarioApiListarUsuariosResponse200 = {
  data: PagedUsuario
  status: 200
}

export type usuarioApiListarUsuariosResponseSuccess = (usuarioApiListarUsuariosResponse200) & {
  headers: Headers;
};
;

export type usuarioApiListarUsuariosResponse = (usuarioApiListarUsuariosResponseSuccess)

export const getUsuarioApiListarUsuariosUrl = (params?: UsuarioApiListarUsuariosParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/usuarios/listar_todos?${stringifiedParams}` : `/api/usuarios/listar_todos`
}

export const usuarioApiListarUsuarios = async (params?: UsuarioApiListarUsuariosParams, options?: RequestInit): Promise<usuarioApiListarUsuariosResponse> => {
  
  const res = await fetch(getUsuarioApiListarUsuariosUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: usuarioApiListarUsuariosResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as usuarioApiListarUsuariosResponse
}
  


/**
 * @summary Listar Sucursales
 */
export type usuarioApiListarSucursalesResponse200 = {
  data: PagedUsuario
  status: 200
}

export type usuarioApiListarSucursalesResponseSuccess = (usuarioApiListarSucursalesResponse200) & {
  headers: Headers;
};
;

export type usuarioApiListarSucursalesResponse = (usuarioApiListarSucursalesResponseSuccess)

export const getUsuarioApiListarSucursalesUrl = (params?: UsuarioApiListarSucursalesParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/usuarios/listar_sucursales?${stringifiedParams}` : `/api/usuarios/listar_sucursales`
}

export const usuarioApiListarSucursales = async (params?: UsuarioApiListarSucursalesParams, options?: RequestInit): Promise<usuarioApiListarSucursalesResponse> => {
  
  const res = await fetch(getUsuarioApiListarSucursalesUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: usuarioApiListarSucursalesResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as usuarioApiListarSucursalesResponse
}
  


/**
 * @summary Listar Sucursales Para Pedido
 */
export type usuarioApiListarSucursalesParaPedidoResponse200 = {
  data: PagedUsuario
  status: 200
}

export type usuarioApiListarSucursalesParaPedidoResponseSuccess = (usuarioApiListarSucursalesParaPedidoResponse200) & {
  headers: Headers;
};
;

export type usuarioApiListarSucursalesParaPedidoResponse = (usuarioApiListarSucursalesParaPedidoResponseSuccess)

export const getUsuarioApiListarSucursalesParaPedidoUrl = (params?: UsuarioApiListarSucursalesParaPedidoParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/usuarios/listar_sucursales_para_pedido?${stringifiedParams}` : `/api/usuarios/listar_sucursales_para_pedido`
}

export const usuarioApiListarSucursalesParaPedido = async (params?: UsuarioApiListarSucursalesParaPedidoParams, options?: RequestInit): Promise<usuarioApiListarSucursalesParaPedidoResponse> => {
  
  const res = await fetch(getUsuarioApiListarSucursalesParaPedidoUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: usuarioApiListarSucursalesParaPedidoResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as usuarioApiListarSucursalesParaPedidoResponse
}
  


/**
 * @summary Obtener Usuario
 */
export type usuarioApiObtenerUsuarioResponse200 = {
  data: Usuario
  status: 200
}

export type usuarioApiObtenerUsuarioResponseSuccess = (usuarioApiObtenerUsuarioResponse200) & {
  headers: Headers;
};
;

export type usuarioApiObtenerUsuarioResponse = (usuarioApiObtenerUsuarioResponseSuccess)

export const getUsuarioApiObtenerUsuarioUrl = (usuarioId: number,) => {


  

  return `/api/usuarios/obtener/${usuarioId}`
}

export const usuarioApiObtenerUsuario = async (usuarioId: number, options?: RequestInit): Promise<usuarioApiObtenerUsuarioResponse> => {
  
  const res = await fetch(getUsuarioApiObtenerUsuarioUrl(usuarioId),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: usuarioApiObtenerUsuarioResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as usuarioApiObtenerUsuarioResponse
}
  


/**
 * Permisos: requiere rol admin.
 * @summary Crear Usuario
 */
export type usuarioApiCrearUsuarioResponse200 = {
  data: Usuario
  status: 200
}

export type usuarioApiCrearUsuarioResponseSuccess = (usuarioApiCrearUsuarioResponse200) & {
  headers: Headers;
};
;

export type usuarioApiCrearUsuarioResponse = (usuarioApiCrearUsuarioResponseSuccess)

export const getUsuarioApiCrearUsuarioUrl = () => {


  

  return `/api/usuarios/crear`
}

export const usuarioApiCrearUsuario = async (usuarioCreate: UsuarioCreate, options?: RequestInit): Promise<usuarioApiCrearUsuarioResponse> => {
  
  const res = await fetch(getUsuarioApiCrearUsuarioUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      usuarioCreate,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: usuarioApiCrearUsuarioResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as usuarioApiCrearUsuarioResponse
}
  


/**
 * Permisos: requiere rol admin.
 * @summary Actualizar Usuario
 */
export type usuarioApiActualizarUsuarioResponse200 = {
  data: Usuario
  status: 200
}

export type usuarioApiActualizarUsuarioResponseSuccess = (usuarioApiActualizarUsuarioResponse200) & {
  headers: Headers;
};
;

export type usuarioApiActualizarUsuarioResponse = (usuarioApiActualizarUsuarioResponseSuccess)

export const getUsuarioApiActualizarUsuarioUrl = (usuarioId: number,) => {


  

  return `/api/usuarios/actualizar/${usuarioId}`
}

export const usuarioApiActualizarUsuario = async (usuarioId: number,
    usuarioUpdate: UsuarioUpdate, options?: RequestInit): Promise<usuarioApiActualizarUsuarioResponse> => {
  
  const res = await fetch(getUsuarioApiActualizarUsuarioUrl(usuarioId),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      usuarioUpdate,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: usuarioApiActualizarUsuarioResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as usuarioApiActualizarUsuarioResponse
}
  


/**
 * @summary Cambiar Mi Contrasena
 */
export type usuarioApiCambiarMiContrasenaResponse200 = {
  data: void
  status: 200
}

export type usuarioApiCambiarMiContrasenaResponseSuccess = (usuarioApiCambiarMiContrasenaResponse200) & {
  headers: Headers;
};
;

export type usuarioApiCambiarMiContrasenaResponse = (usuarioApiCambiarMiContrasenaResponseSuccess)

export const getUsuarioApiCambiarMiContrasenaUrl = () => {


  

  return `/api/usuarios/cambiar_mi_contrasena`
}

export const usuarioApiCambiarMiContrasena = async (cambiarMiContrasena: CambiarMiContrasena, options?: RequestInit): Promise<usuarioApiCambiarMiContrasenaResponse> => {
  
  const res = await fetch(getUsuarioApiCambiarMiContrasenaUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      cambiarMiContrasena,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: usuarioApiCambiarMiContrasenaResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as usuarioApiCambiarMiContrasenaResponse
}
  


/**
 * Permisos: requiere rol admin.
 * @summary Eliminar Usuario
 */
export type usuarioApiEliminarUsuarioResponse200 = {
  data: void
  status: 200
}

export type usuarioApiEliminarUsuarioResponseSuccess = (usuarioApiEliminarUsuarioResponse200) & {
  headers: Headers;
};
;

export type usuarioApiEliminarUsuarioResponse = (usuarioApiEliminarUsuarioResponseSuccess)

export const getUsuarioApiEliminarUsuarioUrl = (usuarioId: number,) => {


  

  return `/api/usuarios/eliminar/${usuarioId}`
}

export const usuarioApiEliminarUsuario = async (usuarioId: number, options?: RequestInit): Promise<usuarioApiEliminarUsuarioResponse> => {
  
  const res = await fetch(getUsuarioApiEliminarUsuarioUrl(usuarioId),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: usuarioApiEliminarUsuarioResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as usuarioApiEliminarUsuarioResponse
}
  


/**
 * @summary Listar Proveedores
 */
export type proveedorApiListarProveedoresResponse200 = {
  data: PagedProveedor
  status: 200
}

export type proveedorApiListarProveedoresResponseSuccess = (proveedorApiListarProveedoresResponse200) & {
  headers: Headers;
};
;

export type proveedorApiListarProveedoresResponse = (proveedorApiListarProveedoresResponseSuccess)

export const getProveedorApiListarProveedoresUrl = (params?: ProveedorApiListarProveedoresParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/proveedores/listar_todos?${stringifiedParams}` : `/api/proveedores/listar_todos`
}

export const proveedorApiListarProveedores = async (params?: ProveedorApiListarProveedoresParams, options?: RequestInit): Promise<proveedorApiListarProveedoresResponse> => {
  
  const res = await fetch(getProveedorApiListarProveedoresUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: proveedorApiListarProveedoresResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as proveedorApiListarProveedoresResponse
}
  


/**
 * @summary Obtener Proveedor
 */
export type proveedorApiObtenerProveedorResponse200 = {
  data: Proveedor
  status: 200
}

export type proveedorApiObtenerProveedorResponseSuccess = (proveedorApiObtenerProveedorResponse200) & {
  headers: Headers;
};
;

export type proveedorApiObtenerProveedorResponse = (proveedorApiObtenerProveedorResponseSuccess)

export const getProveedorApiObtenerProveedorUrl = (proveedorId: number,) => {


  

  return `/api/proveedores/obtener/${proveedorId}`
}

export const proveedorApiObtenerProveedor = async (proveedorId: number, options?: RequestInit): Promise<proveedorApiObtenerProveedorResponse> => {
  
  const res = await fetch(getProveedorApiObtenerProveedorUrl(proveedorId),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: proveedorApiObtenerProveedorResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as proveedorApiObtenerProveedorResponse
}
  


/**
 * @summary Crear Proveedor
 */
export type proveedorApiCrearProveedorResponse200 = {
  data: Proveedor
  status: 200
}

export type proveedorApiCrearProveedorResponseSuccess = (proveedorApiCrearProveedorResponse200) & {
  headers: Headers;
};
;

export type proveedorApiCrearProveedorResponse = (proveedorApiCrearProveedorResponseSuccess)

export const getProveedorApiCrearProveedorUrl = () => {


  

  return `/api/proveedores/crear`
}

export const proveedorApiCrearProveedor = async (proveedorCreate: ProveedorCreate, options?: RequestInit): Promise<proveedorApiCrearProveedorResponse> => {
  
  const res = await fetch(getProveedorApiCrearProveedorUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      proveedorCreate,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: proveedorApiCrearProveedorResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as proveedorApiCrearProveedorResponse
}
  


/**
 * @summary Actualizar Proveedor
 */
export type proveedorApiActualizarProveedorResponse200 = {
  data: Proveedor
  status: 200
}

export type proveedorApiActualizarProveedorResponseSuccess = (proveedorApiActualizarProveedorResponse200) & {
  headers: Headers;
};
;

export type proveedorApiActualizarProveedorResponse = (proveedorApiActualizarProveedorResponseSuccess)

export const getProveedorApiActualizarProveedorUrl = (proveedorId: number,) => {


  

  return `/api/proveedores/actualizar/${proveedorId}`
}

export const proveedorApiActualizarProveedor = async (proveedorId: number,
    proveedorUpdate: ProveedorUpdate, options?: RequestInit): Promise<proveedorApiActualizarProveedorResponse> => {
  
  const res = await fetch(getProveedorApiActualizarProveedorUrl(proveedorId),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      proveedorUpdate,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: proveedorApiActualizarProveedorResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as proveedorApiActualizarProveedorResponse
}
  


/**
 * @summary Eliminar Proveedor
 */
export type proveedorApiEliminarProveedorResponse200 = {
  data: void
  status: 200
}

export type proveedorApiEliminarProveedorResponseSuccess = (proveedorApiEliminarProveedorResponse200) & {
  headers: Headers;
};
;

export type proveedorApiEliminarProveedorResponse = (proveedorApiEliminarProveedorResponseSuccess)

export const getProveedorApiEliminarProveedorUrl = (proveedorId: number,) => {


  

  return `/api/proveedores/eliminar/${proveedorId}`
}

export const proveedorApiEliminarProveedor = async (proveedorId: number, options?: RequestInit): Promise<proveedorApiEliminarProveedorResponse> => {
  
  const res = await fetch(getProveedorApiEliminarProveedorUrl(proveedorId),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: proveedorApiEliminarProveedorResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as proveedorApiEliminarProveedorResponse
}
  


/**
 * @summary Listar Productos Por Proveedor
 */
export type productoApiListarProductosPorProveedorResponse200 = {
  data: PagedProductoList
  status: 200
}

export type productoApiListarProductosPorProveedorResponseSuccess = (productoApiListarProductosPorProveedorResponse200) & {
  headers: Headers;
};
;

export type productoApiListarProductosPorProveedorResponse = (productoApiListarProductosPorProveedorResponseSuccess)

export const getProductoApiListarProductosPorProveedorUrl = (proveedorId: number,
    params?: ProductoApiListarProductosPorProveedorParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/productos/listar_por_proveedor/${proveedorId}?${stringifiedParams}` : `/api/productos/listar_por_proveedor/${proveedorId}`
}

export const productoApiListarProductosPorProveedor = async (proveedorId: number,
    params?: ProductoApiListarProductosPorProveedorParams, options?: RequestInit): Promise<productoApiListarProductosPorProveedorResponse> => {
  
  const res = await fetch(getProductoApiListarProductosPorProveedorUrl(proveedorId,params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: productoApiListarProductosPorProveedorResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as productoApiListarProductosPorProveedorResponse
}
  


/**
 * @summary Listar Productos Todos
 */
export type productoApiListarProductosTodosResponse200 = {
  data: PagedProductoList
  status: 200
}

export type productoApiListarProductosTodosResponseSuccess = (productoApiListarProductosTodosResponse200) & {
  headers: Headers;
};
;

export type productoApiListarProductosTodosResponse = (productoApiListarProductosTodosResponseSuccess)

export const getProductoApiListarProductosTodosUrl = (params?: ProductoApiListarProductosTodosParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/productos/listar_todos?${stringifiedParams}` : `/api/productos/listar_todos`
}

export const productoApiListarProductosTodos = async (params?: ProductoApiListarProductosTodosParams, options?: RequestInit): Promise<productoApiListarProductosTodosResponse> => {
  
  const res = await fetch(getProductoApiListarProductosTodosUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: productoApiListarProductosTodosResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as productoApiListarProductosTodosResponse
}
  


/**
 * @summary Obtener Producto
 */
export type productoApiObtenerProductoResponse200 = {
  data: ProductoDetail
  status: 200
}

export type productoApiObtenerProductoResponseSuccess = (productoApiObtenerProductoResponse200) & {
  headers: Headers;
};
;

export type productoApiObtenerProductoResponse = (productoApiObtenerProductoResponseSuccess)

export const getProductoApiObtenerProductoUrl = (productoId: number,) => {


  

  return `/api/productos/obtener/${productoId}`
}

export const productoApiObtenerProducto = async (productoId: number, options?: RequestInit): Promise<productoApiObtenerProductoResponse> => {
  
  const res = await fetch(getProductoApiObtenerProductoUrl(productoId),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: productoApiObtenerProductoResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as productoApiObtenerProductoResponse
}
  


/**
 * @summary Crear Producto
 */
export type productoApiCrearProductoResponse200 = {
  data: ProductoDetail
  status: 200
}

export type productoApiCrearProductoResponseSuccess = (productoApiCrearProductoResponse200) & {
  headers: Headers;
};
;

export type productoApiCrearProductoResponse = (productoApiCrearProductoResponseSuccess)

export const getProductoApiCrearProductoUrl = () => {


  

  return `/api/productos/crear`
}

export const productoApiCrearProducto = async (productoApiCrearProductoBody: ProductoApiCrearProductoBody, options?: RequestInit): Promise<productoApiCrearProductoResponse> => {
    const formData = new FormData();
if(productoApiCrearProductoBody.imagen !== undefined) {
 formData.append(`imagen`, productoApiCrearProductoBody.imagen);
 }
formData.append(`data`, JSON.stringify(productoApiCrearProductoBody.data));

  const res = await fetch(getProductoApiCrearProductoUrl(),
  {      
    ...options,
    method: 'POST'
    ,
    body: 
      formData,
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: productoApiCrearProductoResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as productoApiCrearProductoResponse
}
  


/**
 * @summary Actualizar Producto
 */
export type productoApiActualizarProductoResponse200 = {
  data: ProductoDetail
  status: 200
}

export type productoApiActualizarProductoResponseSuccess = (productoApiActualizarProductoResponse200) & {
  headers: Headers;
};
;

export type productoApiActualizarProductoResponse = (productoApiActualizarProductoResponseSuccess)

export const getProductoApiActualizarProductoUrl = (productoId: number,) => {


  

  return `/api/productos/actualizar/${productoId}`
}

export const productoApiActualizarProducto = async (productoId: number,
    productoApiActualizarProductoBody: ProductoApiActualizarProductoBody, options?: RequestInit): Promise<productoApiActualizarProductoResponse> => {
    const formData = new FormData();
if(productoApiActualizarProductoBody.imagen !== undefined) {
 formData.append(`imagen`, productoApiActualizarProductoBody.imagen);
 }
formData.append(`data`, JSON.stringify(productoApiActualizarProductoBody.data));

  const res = await fetch(getProductoApiActualizarProductoUrl(productoId),
  {      
    ...options,
    method: 'PATCH'
    ,
    body: 
      formData,
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: productoApiActualizarProductoResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as productoApiActualizarProductoResponse
}
  


/**
 * @summary Eliminar Producto
 */
export type productoApiEliminarProductoResponse200 = {
  data: void
  status: 200
}

export type productoApiEliminarProductoResponseSuccess = (productoApiEliminarProductoResponse200) & {
  headers: Headers;
};
;

export type productoApiEliminarProductoResponse = (productoApiEliminarProductoResponseSuccess)

export const getProductoApiEliminarProductoUrl = (productoId: number,) => {


  

  return `/api/productos/eliminar/${productoId}`
}

export const productoApiEliminarProducto = async (productoId: number, options?: RequestInit): Promise<productoApiEliminarProductoResponse> => {
  
  const res = await fetch(getProductoApiEliminarProductoUrl(productoId),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: productoApiEliminarProductoResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as productoApiEliminarProductoResponse
}
  


/**
 * Permisos: requiere rol admin.
 * @summary Listar Pedidos
 */
export type pedidoApiListarPedidosResponse200 = {
  data: PagedPedido
  status: 200
}

export type pedidoApiListarPedidosResponseSuccess = (pedidoApiListarPedidosResponse200) & {
  headers: Headers;
};
;

export type pedidoApiListarPedidosResponse = (pedidoApiListarPedidosResponseSuccess)

export const getPedidoApiListarPedidosUrl = (params?: PedidoApiListarPedidosParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/pedidos/listar_todos?${stringifiedParams}` : `/api/pedidos/listar_todos`
}

export const pedidoApiListarPedidos = async (params?: PedidoApiListarPedidosParams, options?: RequestInit): Promise<pedidoApiListarPedidosResponse> => {
  
  const res = await fetch(getPedidoApiListarPedidosUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: pedidoApiListarPedidosResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as pedidoApiListarPedidosResponse
}
  


/**
 * @summary Listar Mis Pedidos Hechos
 */
export type pedidoApiListarMisPedidosHechosResponse200 = {
  data: PagedPedido
  status: 200
}

export type pedidoApiListarMisPedidosHechosResponseSuccess = (pedidoApiListarMisPedidosHechosResponse200) & {
  headers: Headers;
};
;

export type pedidoApiListarMisPedidosHechosResponse = (pedidoApiListarMisPedidosHechosResponseSuccess)

export const getPedidoApiListarMisPedidosHechosUrl = (params?: PedidoApiListarMisPedidosHechosParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/pedidos/mis_pedidos_hechos?${stringifiedParams}` : `/api/pedidos/mis_pedidos_hechos`
}

export const pedidoApiListarMisPedidosHechos = async (params?: PedidoApiListarMisPedidosHechosParams, options?: RequestInit): Promise<pedidoApiListarMisPedidosHechosResponse> => {
  
  const res = await fetch(getPedidoApiListarMisPedidosHechosUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: pedidoApiListarMisPedidosHechosResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as pedidoApiListarMisPedidosHechosResponse
}
  


/**
 * @summary Listar Mis Pedidos Recibidos
 */
export type pedidoApiListarMisPedidosRecibidosResponse200 = {
  data: PagedPedido
  status: 200
}

export type pedidoApiListarMisPedidosRecibidosResponseSuccess = (pedidoApiListarMisPedidosRecibidosResponse200) & {
  headers: Headers;
};
;

export type pedidoApiListarMisPedidosRecibidosResponse = (pedidoApiListarMisPedidosRecibidosResponseSuccess)

export const getPedidoApiListarMisPedidosRecibidosUrl = (params?: PedidoApiListarMisPedidosRecibidosParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/pedidos/mis_pedidos_recibidos?${stringifiedParams}` : `/api/pedidos/mis_pedidos_recibidos`
}

export const pedidoApiListarMisPedidosRecibidos = async (params?: PedidoApiListarMisPedidosRecibidosParams, options?: RequestInit): Promise<pedidoApiListarMisPedidosRecibidosResponse> => {
  
  const res = await fetch(getPedidoApiListarMisPedidosRecibidosUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: pedidoApiListarMisPedidosRecibidosResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as pedidoApiListarMisPedidosRecibidosResponse
}
  


/**
 * @summary Obtener Pedido
 */
export type pedidoApiObtenerPedidoResponse200 = {
  data: Pedido
  status: 200
}

export type pedidoApiObtenerPedidoResponseSuccess = (pedidoApiObtenerPedidoResponse200) & {
  headers: Headers;
};
;

export type pedidoApiObtenerPedidoResponse = (pedidoApiObtenerPedidoResponseSuccess)

export const getPedidoApiObtenerPedidoUrl = (pedidoId: number,) => {


  

  return `/api/pedidos/obtener/${pedidoId}`
}

export const pedidoApiObtenerPedido = async (pedidoId: number, options?: RequestInit): Promise<pedidoApiObtenerPedidoResponse> => {
  
  const res = await fetch(getPedidoApiObtenerPedidoUrl(pedidoId),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: pedidoApiObtenerPedidoResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as pedidoApiObtenerPedidoResponse
}
  


/**
 * @summary Copiar Pedido Completo
 */
export type pedidoApiCopiarPedidoCompletoResponse200 = {
  data: PedidoCopiaResumen
  status: 200
}

export type pedidoApiCopiarPedidoCompletoResponseSuccess = (pedidoApiCopiarPedidoCompletoResponse200) & {
  headers: Headers;
};
;

export type pedidoApiCopiarPedidoCompletoResponse = (pedidoApiCopiarPedidoCompletoResponseSuccess)

export const getPedidoApiCopiarPedidoCompletoUrl = (pedidoId: number,) => {


  

  return `/api/pedidos/copiar_pedido/completo/${pedidoId}`
}

export const pedidoApiCopiarPedidoCompleto = async (pedidoId: number, options?: RequestInit): Promise<pedidoApiCopiarPedidoCompletoResponse> => {
  
  const res = await fetch(getPedidoApiCopiarPedidoCompletoUrl(pedidoId),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: pedidoApiCopiarPedidoCompletoResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as pedidoApiCopiarPedidoCompletoResponse
}
  


/**
 * @summary Copiar Pedido Por Proveedor
 */
export type pedidoApiCopiarPedidoPorProveedorResponse200 = {
  data: PedidoCopiaResumen
  status: 200
}

export type pedidoApiCopiarPedidoPorProveedorResponseSuccess = (pedidoApiCopiarPedidoPorProveedorResponse200) & {
  headers: Headers;
};
;

export type pedidoApiCopiarPedidoPorProveedorResponse = (pedidoApiCopiarPedidoPorProveedorResponseSuccess)

export const getPedidoApiCopiarPedidoPorProveedorUrl = (pedidoId: number,
    proveedorId: number,) => {


  

  return `/api/pedidos/copiar_pedido/por_proveedor/${pedidoId}/${proveedorId}`
}

export const pedidoApiCopiarPedidoPorProveedor = async (pedidoId: number,
    proveedorId: number, options?: RequestInit): Promise<pedidoApiCopiarPedidoPorProveedorResponse> => {
  
  const res = await fetch(getPedidoApiCopiarPedidoPorProveedorUrl(pedidoId,proveedorId),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: pedidoApiCopiarPedidoPorProveedorResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as pedidoApiCopiarPedidoPorProveedorResponse
}
  


/**
 * @summary Crear Pedido
 */
export type pedidoApiCrearPedidoResponse200 = {
  data: Pedido
  status: 200
}

export type pedidoApiCrearPedidoResponseSuccess = (pedidoApiCrearPedidoResponse200) & {
  headers: Headers;
};
;

export type pedidoApiCrearPedidoResponse = (pedidoApiCrearPedidoResponseSuccess)

export const getPedidoApiCrearPedidoUrl = () => {


  

  return `/api/pedidos/crear`
}

export const pedidoApiCrearPedido = async (pedidoCreate: PedidoCreate, options?: RequestInit): Promise<pedidoApiCrearPedidoResponse> => {
  
  const res = await fetch(getPedidoApiCrearPedidoUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      pedidoCreate,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: pedidoApiCrearPedidoResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as pedidoApiCrearPedidoResponse
}
  


/**
 * @summary Actualizar Pedido
 */
export type pedidoApiActualizarPedidoResponse200 = {
  data: Pedido
  status: 200
}

export type pedidoApiActualizarPedidoResponseSuccess = (pedidoApiActualizarPedidoResponse200) & {
  headers: Headers;
};
;

export type pedidoApiActualizarPedidoResponse = (pedidoApiActualizarPedidoResponseSuccess)

export const getPedidoApiActualizarPedidoUrl = (pedidoId: number,) => {


  

  return `/api/pedidos/actualizar/${pedidoId}`
}

export const pedidoApiActualizarPedido = async (pedidoId: number,
    pedidoUpdate: PedidoUpdate, options?: RequestInit): Promise<pedidoApiActualizarPedidoResponse> => {
  
  const res = await fetch(getPedidoApiActualizarPedidoUrl(pedidoId),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      pedidoUpdate,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: pedidoApiActualizarPedidoResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as pedidoApiActualizarPedidoResponse
}
  


/**
 * @summary Cambiar Estado Pedido
 */
export type pedidoApiCambiarEstadoPedidoResponse200 = {
  data: Pedido
  status: 200
}

export type pedidoApiCambiarEstadoPedidoResponseSuccess = (pedidoApiCambiarEstadoPedidoResponse200) & {
  headers: Headers;
};
;

export type pedidoApiCambiarEstadoPedidoResponse = (pedidoApiCambiarEstadoPedidoResponseSuccess)

export const getPedidoApiCambiarEstadoPedidoUrl = (pedidoId: number,) => {


  

  return `/api/pedidos/cambiar_estado/${pedidoId}`
}

export const pedidoApiCambiarEstadoPedido = async (pedidoId: number,
    pedidoCambiarEstado: PedidoCambiarEstado, options?: RequestInit): Promise<pedidoApiCambiarEstadoPedidoResponse> => {
  
  const res = await fetch(getPedidoApiCambiarEstadoPedidoUrl(pedidoId),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      pedidoCambiarEstado,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: pedidoApiCambiarEstadoPedidoResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as pedidoApiCambiarEstadoPedidoResponse
}
  


/**
 * @summary Eliminar Pedido
 */
export type pedidoApiEliminarPedidoResponse200 = {
  data: void
  status: 200
}

export type pedidoApiEliminarPedidoResponseSuccess = (pedidoApiEliminarPedidoResponse200) & {
  headers: Headers;
};
;

export type pedidoApiEliminarPedidoResponse = (pedidoApiEliminarPedidoResponseSuccess)

export const getPedidoApiEliminarPedidoUrl = (pedidoId: number,) => {


  

  return `/api/pedidos/eliminar/${pedidoId}`
}

export const pedidoApiEliminarPedido = async (pedidoId: number, options?: RequestInit): Promise<pedidoApiEliminarPedidoResponse> => {
  
  const res = await fetch(getPedidoApiEliminarPedidoUrl(pedidoId),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: pedidoApiEliminarPedidoResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as pedidoApiEliminarPedidoResponse
}
  


/**
 * @summary Listar Productos Pedido Por Proveedor
 */
export type pedidoApiListarProductosPedidoPorProveedorResponse200 = {
  data: PagedPedidoDetalle
  status: 200
}

export type pedidoApiListarProductosPedidoPorProveedorResponseSuccess = (pedidoApiListarProductosPedidoPorProveedorResponse200) & {
  headers: Headers;
};
;

export type pedidoApiListarProductosPedidoPorProveedorResponse = (pedidoApiListarProductosPedidoPorProveedorResponseSuccess)

export const getPedidoApiListarProductosPedidoPorProveedorUrl = (pedidoId: number,
    proveedorId: number,
    params?: PedidoApiListarProductosPedidoPorProveedorParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/pedidos/productos_pedido/por_pedido/${pedidoId}/proveedor/${proveedorId}?${stringifiedParams}` : `/api/pedidos/productos_pedido/por_pedido/${pedidoId}/proveedor/${proveedorId}`
}

export const pedidoApiListarProductosPedidoPorProveedor = async (pedidoId: number,
    proveedorId: number,
    params?: PedidoApiListarProductosPedidoPorProveedorParams, options?: RequestInit): Promise<pedidoApiListarProductosPedidoPorProveedorResponse> => {
  
  const res = await fetch(getPedidoApiListarProductosPedidoPorProveedorUrl(pedidoId,proveedorId,params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: pedidoApiListarProductosPedidoPorProveedorResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as pedidoApiListarProductosPedidoPorProveedorResponse
}
  


/**
 * @summary Listar Proveedores Resumen Por Pedido
 */
export type pedidoApiListarProveedoresResumenPorPedidoResponse200 = {
  data: PagedPedidoProveedorResumen
  status: 200
}

export type pedidoApiListarProveedoresResumenPorPedidoResponseSuccess = (pedidoApiListarProveedoresResumenPorPedidoResponse200) & {
  headers: Headers;
};
;

export type pedidoApiListarProveedoresResumenPorPedidoResponse = (pedidoApiListarProveedoresResumenPorPedidoResponseSuccess)

export const getPedidoApiListarProveedoresResumenPorPedidoUrl = (pedidoId: number,
    params?: PedidoApiListarProveedoresResumenPorPedidoParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/pedidos/proveedores_resumen/por_pedido/${pedidoId}?${stringifiedParams}` : `/api/pedidos/proveedores_resumen/por_pedido/${pedidoId}`
}

export const pedidoApiListarProveedoresResumenPorPedido = async (pedidoId: number,
    params?: PedidoApiListarProveedoresResumenPorPedidoParams, options?: RequestInit): Promise<pedidoApiListarProveedoresResumenPorPedidoResponse> => {
  
  const res = await fetch(getPedidoApiListarProveedoresResumenPorPedidoUrl(pedidoId,params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: pedidoApiListarProveedoresResumenPorPedidoResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as pedidoApiListarProveedoresResumenPorPedidoResponse
}
  


/**
 * @summary Crear Producto Pedido
 */
export type pedidoApiCrearProductoPedidoResponse200 = {
  data: PedidoDetalle
  status: 200
}

export type pedidoApiCrearProductoPedidoResponseSuccess = (pedidoApiCrearProductoPedidoResponse200) & {
  headers: Headers;
};
;

export type pedidoApiCrearProductoPedidoResponse = (pedidoApiCrearProductoPedidoResponseSuccess)

export const getPedidoApiCrearProductoPedidoUrl = () => {


  

  return `/api/pedidos/productos_pedido/crear`
}

export const pedidoApiCrearProductoPedido = async (pedidoDetalleCreate: PedidoDetalleCreate, options?: RequestInit): Promise<pedidoApiCrearProductoPedidoResponse> => {
  
  const res = await fetch(getPedidoApiCrearProductoPedidoUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      pedidoDetalleCreate,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: pedidoApiCrearProductoPedidoResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as pedidoApiCrearProductoPedidoResponse
}
  


/**
 * @summary Actualizar Producto Pedido
 */
export type pedidoApiActualizarProductoPedidoResponse200 = {
  data: PedidoDetalle
  status: 200
}

export type pedidoApiActualizarProductoPedidoResponseSuccess = (pedidoApiActualizarProductoPedidoResponse200) & {
  headers: Headers;
};
;

export type pedidoApiActualizarProductoPedidoResponse = (pedidoApiActualizarProductoPedidoResponseSuccess)

export const getPedidoApiActualizarProductoPedidoUrl = (productoPedidoId: number,) => {


  

  return `/api/pedidos/productos_pedido/actualizar/${productoPedidoId}`
}

export const pedidoApiActualizarProductoPedido = async (productoPedidoId: number,
    pedidoDetalleUpdate: PedidoDetalleUpdate, options?: RequestInit): Promise<pedidoApiActualizarProductoPedidoResponse> => {
  
  const res = await fetch(getPedidoApiActualizarProductoPedidoUrl(productoPedidoId),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      pedidoDetalleUpdate,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: pedidoApiActualizarProductoPedidoResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as pedidoApiActualizarProductoPedidoResponse
}
  


/**
 * @summary Eliminar Producto Pedido
 */
export type pedidoApiEliminarProductoPedidoResponse200 = {
  data: void
  status: 200
}

export type pedidoApiEliminarProductoPedidoResponseSuccess = (pedidoApiEliminarProductoPedidoResponse200) & {
  headers: Headers;
};
;

export type pedidoApiEliminarProductoPedidoResponse = (pedidoApiEliminarProductoPedidoResponseSuccess)

export const getPedidoApiEliminarProductoPedidoUrl = (productoPedidoId: number,) => {


  

  return `/api/pedidos/productos_pedido/eliminar/${productoPedidoId}`
}

export const pedidoApiEliminarProductoPedido = async (productoPedidoId: number, options?: RequestInit): Promise<pedidoApiEliminarProductoPedidoResponse> => {
  
  const res = await fetch(getPedidoApiEliminarProductoPedidoUrl(productoPedidoId),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: pedidoApiEliminarProductoPedidoResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as pedidoApiEliminarProductoPedidoResponse
}
  


/**
 * @summary Obtener Estadisticas
 */
export type dashboardApiObtenerEstadisticasResponse200 = {
  data: DashboardEstadisticas
  status: 200
}

export type dashboardApiObtenerEstadisticasResponseSuccess = (dashboardApiObtenerEstadisticasResponse200) & {
  headers: Headers;
};
;

export type dashboardApiObtenerEstadisticasResponse = (dashboardApiObtenerEstadisticasResponseSuccess)

export const getDashboardApiObtenerEstadisticasUrl = () => {


  

  return `/api/dashboard/estadisticas`
}

export const dashboardApiObtenerEstadisticas = async ( options?: RequestInit): Promise<dashboardApiObtenerEstadisticasResponse> => {
  
  const res = await fetch(getDashboardApiObtenerEstadisticasUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: dashboardApiObtenerEstadisticasResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as dashboardApiObtenerEstadisticasResponse
}
